name: bdaya_openidconnect
description: OpenIdConnect library for flutter, it supports interactive authorization and token refresh/persistance.
version: 1.0.0
homepage: https://github.com/Bdaya-Dev/openidconnect_flutter
repository: https://github.com/Bdaya-Dev/openidconnect_flutter/tree/main/openidconnect

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  bdaya_openidconnect_platform_interface: ^1.0.2
  bdaya_openidconnect_web: ^1.0.0
  bdaya_openidconnect_windows: ^0.0.1
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1

  cryptography: ^2.0.5

  url_launcher: ^6.1.6
  http: ^0.13.5
  retry: ^3.1.0

  # TODO Remove these once native implementations can be added. Refactor so that the native implementations don't need to do the full cycle through.
  webview_flutter: ^4.0.7
  async: ^2.10.0
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      ios:
        dartPluginClass: OpenIdConnectAndroidiOS
        fileName: src/android_ios.dart
      android:
        dartPluginClass: OpenIdConnectAndroidiOS
        fileName: src/android_ios.dart
      web:
        default_package: bdaya_openidconnect_web
      windows:
        default_package: bdaya_openidconnect_windows
