name: openidconnect_platform_interface
version: 1.0.13
homepage: https://github.com/Bdaya-dev/openidconnect_flutter/tree/main/openidconnect_platform_interface
publish_to: https://onepub.dev/api/snssdavuhn/
description: Platform interface for OpenIdConnect.
environment: 
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=2.8.0'
dependencies: 
  plugin_platform_interface: ^2.1.3
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.1
  mockito: ^5.3.2
  flutter_test: 
    sdk: flutter
