name: bdaya_openidconnect_windows
description: Windows implementation for OpenIdConnect.
version: 0.0.1
homepage: https://github.com/Bdaya-Dev/openidconnect_flutter/tree/main/openidconnect_windows

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  bdaya_openidconnect_platform_interface: ^1.0.2
  webview_windows: ^0.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: bdaya_openidconnect
    platforms:
      windows:
        dartPluginClass: OpenIdConnectWindows
        fileName: openidconnect_windows.dart
