name: openidconnect_windows
description: Windows implementation for OpenIdConnect.
version: 0.0.7
publish_to: https://onepub.dev/api/snssdavuhn/
homepage: https://gitlab.com/bdaya-dev/packages/openidconnect/-/tree/main/openidconnect_windows

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  openidconnect_platform_interface: 
    hosted: https://onepub.dev/api/snssdavuhn/
    version: ^1.0.11
  webview_windows: ^0.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: openidconnect
    platforms:
      windows:
        dartPluginClass: OpenIdConnectWindows
        fileName: openidconnect_windows.dart
